### ISSUE TITLE
Heading changes

### ISSUE THREAD

**Issue by pgmoir** [pgmoir/millionmilesformyeloma#9]
Just tested it! It works perfectly! Thank you!

Two minor things, firstly, would it be possible in the title to heading to spell out The Basil Skyers Myeloma Foundation and then under that have 'A Million Miles....

In the footer, after the phrase '.....submitting your miles to:  Would it also be possible to insert The Basil Skyers Myeloma Foundation before 'A Million....

The reason is, Myeloma UK is bigger than we are. We work really well with them but want to promote our name strongly otherwise it may not be associated with us.

The only other thing is changing the myeloma text very slightly and I will do that now and send it separately.

I think the supported by footer is great!

It is great! Thank you!

**Comment by pgmoir** [comment]
having an issue trying to not take up too much space at top of page with headings so slipped in the Basil Skyers into the menu and kept the h1 as the million miles tag.

**Comment by pgmoir** [comment]
Updated the success footer to read "Well done! Thank you so much for submitting your miles to The Basil Skyers Myeloma Foundation's "A Million Miles for Multiple Myeloma". Together we have achieved 13 miles! We hope you enjoyed your cycle."

**Comment by calummoir** [comment]
The Basil Skyers title is being reduced on large screens

**Comment by pgmoir** [comment]
Managed to limit size of heading on larger screens so that the text cut off does not occur.
